# -*- coding: utf-8 -*-
"""Backend para site de cadastro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vsouRYaDUyhBdFNoys1DhoWoDILe6TM
"""

# Código para execução para que vincule um site em um banco de Dados #


from flask import Flask, request, jsonify
from dotenv import load_dotenv
import mysql.connector
import os

load_dotenv()  # Carrega variáveis do .env

app = Flask(__name__)

def get_db_connection():
    return mysql.connector.connect(
        host=os.getenv("MYSQL_ADDON_HOST"),
        user=os.getenv("MYSQL_ADDON_USER"),
        password=os.getenv("MYSQL_ADDON_PASSWORD"),
        database=os.getenv("MYSQL_ADDON_DB"),
        port=int(os.getenv("MYSQL_ADDON_PORT", 3306))
    )

@app.route("/cadastro", methods=["POST"])
def cadastro():
    data = request.get_json()
    nome = data.get("nome")
    email = data.get("email")

    if not nome or not email:
        return jsonify({"erro": "Nome e e-mail são obrigatórios."}), 400

    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("INSERT INTO usuarios (nome, email) VALUES (%s, %s)", (nome, email))
        conn.commit()
        cursor.close()
        conn.close()
        return jsonify({"mensagem": "Usuário cadastrado com sucesso."})
    except mysql.connector.Error as err:
        return jsonify({"erro": str(err)}), 500

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)